### ISSUE TITLE
Multishop feature

### ISSUE THREAD

**Issue by syntaxlb** [doofinder/doofinder-prestashop#12]
Hi,

On my prestashop i have multiple shop, with multiple prices for each product

Ex: 
Price for Product A in Shop A = 2€
Price for Product A in Shop B = 4€

How can I use Doofinder with different prices depending on the shop?
Because the data feed seems to take the prices of the default shop (Shop A) only

**Comment by danidomen** [comment]
I checked and work as expected (each domain export the price of each shop associated with its domain)

Remember that you must use each feed with the domain of the shop. That is:
- https://myshopA.com/modules/doofinder/feed.php?language=ES&currency=EUR will export your price on Shop A
- https://myshopB.com/modules/doofinder/feed.php?language=ES&currency=EUR will export your price on Shop B

If you want on the same feed export the different prices for each shop, this is not possible and you or you agency/developer must rewrite as your needs.

**Comment by danidomen** [comment]
Hi @kataklanka I think this can be closed.
