### ISSUE TITLE
Error on updgrade: Cannot redeclare installDb

### ISSUE THREAD

**Issue by carcam** [doofinder/doofinder-prestashop#134]
Hi,
I'm trying to upload the module from 4.1.4 to latest 4.6.2 and I get the following error on install:

> Compile Error: Cannot redeclare installDb() (previously declared in modules/doofinder/upgrade/upgrade-4.2.0.php:39)

Can you please help?

Thanks!!

**Comment by ivan-doofinder** [comment]
Version 4.6.2 is not released yet

**Comment by carcam** [comment]
Thank you for your reply!! 

I meant the 4.6.1: 

https://github.com/doofinder/doofinder-prestashop/releases/download/v4.6.1/doofinder-prestashop.zip

Sorry for the misunderstanding. Any ideas on what could be the issue?

**Comment by ivan-doofinder** [comment]
> Thank you for your reply!!
> 
> I meant the 4.6.1:
> 
> https://github.com/doofinder/doofinder-prestashop/releases/download/v4.6.1/doofinder-prestashop.zip
> 
> Sorry for the misunderstanding. Any ideas on what could be the issue?

we check it

**Comment by frobs** [comment]
Hello @carcam  this issue is fixed in the new release 4.6.3

**Comment by carcam** [comment]
Thanks @frobs !! I have installed the release and I confirm there are no issues.
