### ISSUE TITLE
Fix Sentry - Prestashop Update On Save - Empty payload

### ISSUE THREAD

**Issue by pedromcp90** [doofinder/doofinder-prestashop#141]
We have identified an [issue](https://doofindercom.sentry.io/issues/4275981407) in Sentry that appears to be triggered by sending requests to the product_update endpoint with an empty payload.

To prevent unnecessary requests to doomanager, we should implement a check before sending the request to ensure that there are products available for updating.

**Comment by ivan-doofinder** [comment]
If you want to avoid processing an empty request, I think this check should be done in doomanager.

**Comment by davidmolinacano** [comment]
Although this task is already fixed from Prestashop side, We'll apply also a guard from DooManager's side
