### ISSUE TITLE
MPN in Prestashop

### ISSUE THREAD

**Issue by davidmolinacano** [doofinder/doofinder-prestashop#154]
Related to: https://github.com/doofinder/support/issues/1687

Prestashop must index all fields. The MPN field should be taken as such and not assumed to be the Reference. Previously, customers could choose which field should serve as MPN, but this was removed at the request of Product (See https://github.com/doofinder/doofinder-prestashop/pull/48). However, the idea was to index all the fields and not assuming that the MPN will be the reference

**Comment by sofia-doofinder** [comment]
Por lo que se ve en el PR  (https://github.com/doofinder/support/issues/1687), se podía elegir en el plugin que en el campo mpn se pudiera indexar el valor de uno de estos campos: reference, supplier_reference, ean13 y upc, pero el campo mpn parece que nunca se podía elegir como valor. He visto que actualmente estos campos se están indexando:
- reference
- supplier_reference
- ean13
- upc

pero el valor del campo mpn nunca se indexa, en su lugar se vuelve a indexar el valor de `reference` con el nombre `mpn`.

![Image](https://github.com/doofinder/doofinder-prestashop/assets/92720455/6b3256e8-e528-4f35-a1eb-4f578620ee2d)

se ha hablado con @CristobalDolz que el fix aquí sería que indexemos el valor real que tienen prestashop del mpn en el campo mpn.
