### ISSUE TITLE
[Prestashop] Add conversion page theme config

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#171]
Se tiene que terminar de definir. Pero para evitar errores con los temas se plantea como solución permitir que el usuario introduzca el nombre del fichero de su tema que se encarga de pintar el listado de productos.

Habrá una parte de la implementación que la llevará a cabo doom (admin de doofinder) y en plugins deberemos obtener estos datos para la carga de la conversion page.

![Image](https://github.com/doofinder/doofinder-prestashop/assets/92720455/a0453ed4-bb8e-48cd-a42e-c16cd6bee54a)

----------

Edito la tarea con la información de notion:

# NEED TO SOLVE

En la fase de beta testing que hemos lanzado en Conversion pages con Prestashop España ha surgido varios problemas de error 500 a la hora de renderizar la landing pages debido a que no se encontraba el template en la ruta por defecto que se esperaba para renderizar los productos.

Issue soporte:

- [https://github.com/doofinder/support/issues/1731#issuecomment-1761229724](https://github.com/doofinder/support/issues/1731#issuecomment-1761229724)
- muebles de casa.net

![image](https://github.com/doofinder/doofinder-prestashop/assets/92720455/a31b1f75-d9bd-425c-a854-0b2019c5caa5)

Hasta ahora los problemas se han solventado pidiendo al cliente que cree el template de productos del tema que utiliza a la ruta por defecto esperada.

# USER VALUE

| “WHY does it need?” |
| --- |
- Es imprescindible que las landing pages utilicen el tema de la tienda
- Si no se encuentra el template de productos del tema no se renderiza la landing pages (error 500)

| “WHO does it need for?” |
| --- |
- Usuarios de conversion pages de Prestashop

| “WHAT would success mean for that need?” |
| --- |
- Evitar el error 500 al no encontrar el template de productos del tema
- Evitar que la solución sea que el cliente necesite mover el template a la ruta esperada.

# **PROJECT DEFINITION**

| REQUIREMENTS: |
| --- |

Buscar la manera de indicar dónde se encuentra el template de productos del tema utilizado en caso de no cumplir con el estandard.

Es lo mismo que se ha hecho en Shopify

Este campo es común para toda la store por lo que puede ser una configuración genérica para todas las páginas.

- Si por defecto encontramos el template del tema, rellenar el campo por defecto.
    - El fichero por defecto que usa Prestashop se llama**`productlist.tpl`** y se espera encontrar en la ruta: **`/templates/catalog/_partials/productlist.tpl`**
- En caso de no encontrar el template del tema, entonces;
    - dejar el campo vacío
    - pedir como primer paso que el usuario complete indique el template
    - No permitir crear páginas nuevas hasta que el campo esté completado

mock up: podría cambiar en función de cómo se tuviera que rellenar el campo

![image](https://github.com/doofinder/doofinder-prestashop/assets/92720455/da943241-7e7e-481e-87d6-7613e6917496)

**Comment by ivan-doofinder** [comment]
¿Se ha dado algún caso en el que el usuario tenga el productlist.tpl en otro fichero?

**Comment by sofia-doofinder** [comment]
en los casos que te has encontrado, el cliente lo tenía en otra ruta? su tema tenía otro fichero? o cómo ha sido exactamente?

**Comment by ivan-doofinder** [comment]
Aun no me ha salido ningún caso de estos a mi. @vferrero tuvo alguno y era porque el fichero no existía

**Comment by vferrero** [comment]
Si, los 2 casos que yo vi la semana de soporte era justo que no existía el fichero, y parece ser que copiandolo en la ruta correcta se solucionaba.

**Comment by sofia-doofinder** [comment]
y un par de preguntas @ivan-doofinder .  Si el cliente no tenía ese fichero, y no hay uno que lo "sustituya" en su template, cómo es que le funciona la tienda y la carga de listado de productos?

Y la otra, en los casos de los clientes del listado que pasó Cristobal, ¿qué tipo de errores te has encontrado? También has tenido que ponerles ese fichero en sus templates?


@CristobalDolz te menciono para que tengas visibilidad. Por lo que parece en prestashop no es que haya que apuntar a otro fichero si no que el fichero no está. No se si sería una "solución" poner en la sección de config de la landing un enlace al fichero en el github de prestashop o algo por el estilo y explicarles que tienen que descargarlo y ponerlo en su carpeta del template...

**Comment by ivan-doofinder** [comment]
@sofia-doofinder en esos casos que comentas les funciona porque el "foreach" de los productos los hacen en la plantilla "padre" (category, manufacturer, etc), en vez de tener un tpl encargado de mostrar únicamente los productos.

Los casos que he visto, uno era un problema (algo de su plataforma) con la redirección de la URL que aparece en el admin a la landing. La landing funcionaba bien.
Otro era que no tenía en base de datos información sobre los search engines, seguramente porque actualizó desde una versión muy antigua. Solo con darle a "Guardar" en el módulo, sin tocar nada más se solucionó.

**Comment by CristobalDolz** [comment]
@sofia-doofinder lo pusimos en la documentación de soporte. 
![image](https://github.com/doofinder/doofinder-prestashop/assets/106097983/b95e6e9e-4a62-458b-8c21-de337233eee3)

Si para este problema realmente valorais que no hay otra solución que crear el fichero en la carpeta del template ¿Sería posible detectarlo con antelación y mostrar un aviso?

**Comment by ivan-doofinder** [comment]
A partir de la versión 4.7.16, el productlist.tpl irá integrado en el plugin, para evitar problemas en usuarios que no tengan ese fichero en su plantilla
