### ISSUE TITLE
[Prestashop] Investigar mostrar actualizaciones plugin Prestashop en Module Manager

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#172]
# NEED TO SOLVE

---

| ISSUE/OPPORTUNITY DESCRIPTION:  |
| --- |

Los clientes suelen tener versiones muy antiguas de Prestashop porque cuando lanzamos una nueva versión no avisamos de que hay una actualización disponible.

En el Module Manager hay un apartado de actualizaciones disponibles en el que no aparecemos

![image](https://github.com/doofinder/doofinder-prestashop/assets/92720455/997fcfcb-8f85-404d-a4fe-8dcf427a2bac)

| OTHER RELEVANT INFORMATION: if exists |
| --- |

No sabemos si es una sección especial para los módulos que paguen por ello o es una configuración del módulo que no tenemos.

# USER VALUE

| “WHY does it need?” |
| --- |
- Para que los usuarios actualicen las nuevas versiones

| “WHO does it need for?” |
| --- |
- Usarios prestashop

| “WHAT would success mean for that need?” |
| --- |
- Indicar qué tiene esa actualización.

# **PROJECT DEFINITION**

---

| REQUIREMENTS: |
| --- |

Investigar qué hay que hacer para aparecer en Updates cuando haya una versión disponible para actualizar posterior a la que el cliente tenga instalada.

¿Existe alguna configuración para mostrar esas notificaciones?

**Comment by ivan-doofinder** [comment]
@CristobalDolz he estado investigando y no hay forma de que nuestro módulo aparezca ahí.

Aparecen únicamente los módulos creados por Prestashop. Y según indica, pueden aparecer los módulos que compres en el Addons, si tienes la cuenta conectada. Pero nuestro módulo al no poder comprarse, nunca se asocia a la cuenta del usuario.
Se supone que en el addons los módulos comprados aparecen aquí:
![Image](https://github.com/doofinder/doofinder-prestashop/assets/97448277/62842552-d36a-4af9-ab56-932932def1aa)


Una opción que tenemos es mostrar un mensaje dentro del módulo, informando de que hay una nueva versión. Lo que pasa es que eso lo verán los usuarios únicamente si acceden a la configuración del módulo.

También se podría ver la posibilidad de hacer un desarrollo para que muestre en esta parte del dashboard un mensaje informando de que hay una nueva versión de nuestro módulo, aunque puede ser algo intrusivo mostrar ahí eso...


![Image](https://github.com/doofinder/doofinder-prestashop/assets/97448277/271a60a2-6dc5-47d1-b418-69d9b83034d3)

**Comment by CristobalDolz** [comment]
Gracias por la información @ivan-doofinder
