### ISSUE TITLE
[Prestashop] Index default category

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#183]
Actualmente estamos indexando todo el árbol de categorías de un producto. Pero prestashop permite seleccionar una categoría como la principal. Sería necesario añadir al feed este campo `main_category` para ser indexado.

**Comment by brunovesar** [comment]
Por lo que entiendo el cambio debería hacerse en feeds/product.php en el que deberíamos agregar un header ¨main_category" y un valor para cada product.
El nombre de la main category debe ser traducido con la tabla category_lang a partir del id de la categoria en el archivo dfTools.
Veo también que hay un archivo dfProduct_build que también parece que mapea los productos, entiendo que también debería agregarlo ahí.
@pedromcp90 Te parece que tiene sentido así?

**Comment by brunovesar** [comment]
Al probar el código me di cuenta de que el id de la categoría no estaba viniendo, así que revisé el método getAvailableProducts y encontré un bug.
Se estaba parseando el __ID_CATEGORY_DEFAULT__ a int, cuando en realidad era un string, y eso hacía que no apareciera ninguna categoria.
Arreglando eso vi que ya estamos haciendo el join con category_lang así que directamente agregué el main_category al product para devolverlo en el feed
