### ISSUE TITLE
[Prestashop] Modify update on save configuration

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#185]
Required by: https://github.com/doofinder/support/issues/2164

Actualmente el cliente tiene estas opciones a la hora de configurar el update on save en el plugin:

![Image](https://github.com/doofinder/doofinder-prestashop/assets/92720455/08e9e85d-0773-4dc9-b642-e8f4d6013c4a)

Cuando el cliente selecciona la opción `everyday` en realidad no está utilizando el update on save, si no que se deja la  modificación del feed en manos de la reindexación diaria que hace dftasks. 

Esto puede llevar a confusión a algunos clientes, por lo que se va a modificar para tener esto dividido en dos opciones:
- Update On save con un switch para activar o desactivar. Podemos mantener la etiqueta de "Update on save"
- Si está a true entonces los valores a elegir en el selector son: 90, 60, 30, 15 minutes. Utilizar la etiqueta "Process changed products"

Si hay alguna duda hablar con @CristobalDolz

**Comment by brunovesar** [comment]
Como se discutió en https://github.com/doofinder/doofinder-woocommerce/issues/264 finalmente cambiaremos la opción every day por disabled
