### ISSUE TITLE
[Prestashop] sale_price de producto padre

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#198]
Parece que no estamos indexando correctamente el sale price del producto padre de los productos configurables.

El producto padre, debería indexar el sale_price más bajo del grupo de variaciones. Es decir, que si en el grupo de variaciones, uno de ellas tiene un descuento, el producto padre debería incluirlo también.

**Comment by kataklanka** [comment]
@sofia-doofinder, esto empieza a ser prioritario, tenemos tickets por este problema que tenemos que resolver excluyendo los productos padre y ordenando por best_price ascending:

https://doofinder.freshdesk.com/a/tickets/162860

Pasa lo mismo en Wordpress.

**Comment by ogomezba** [comment]
@kataklanka Hola Alfonso! Ya está disponible la nueva release en el Marketplace para descargar. Con la nueva release, este problema ya debería estar resuelto y las nuevas indexaciones deberían indexar el precio del padre correctamente. Si hay cualquier problema me dices!
