### ISSUE TITLE
[Est:2] [Prestashop] Cambiar el uso de la API 5 por la 6

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#208]
Parece que prestashop está usando la versión de la API de doofinder v5 en lugar de la v6.
https://github.com/doofinder/doofinder-prestashop/blob/master/lib/doofinder_api.php#L35

Esto parece que actualmente se utiliza para las landing pages, pero debería modificarse para utilizar la v6.

Es posible que se estuviera utilizando la v5 porque es la que se empezó a utilizar en el plugin y por algún motivo nunca se ha actualizado. Antes se utilizaba para el update on save y la búsqueda nativa, pero el update on save ahora se hace a través de dooplugins y la búsqueda nativa se quitó del plugin, por lo que sólo se debe de utilizar en la landing pero **habría que revisarlo**.

**Comment by eduardogomez97** [comment]
He modificado a la v6 y he testeado que todo funcione como es debido. En principio no da problemas.

![Image](https://github.com/user-attachments/assets/2f4c9374-8a62-4228-b925-b3a6d1d7bdc0)


Solo se utiliza además para hacer un test de que funciona la propia API. $this->testDoofinderApi();

**Comment by eduardogomez97** [comment]
Ya está publicada la nueva versión y funcionando!
