### ISSUE TITLE
[Unique script] - Prestashop

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-prestashop#211]
An endpoint must be created to receive the new script and add it to the plugin database in order to carry out the substitution.

Important the add_to_cart is concatenated to this script.

Test the endpoint to check that everything is working correctly. The call to this endpoint should only be made in case it is safe to replace the script, i.e., it may annoy a client with a modified script.

**Comment by sofia-doofinder** [comment]
otra cosa, tenemos que modificar el script que está definido en el plugin para que sea el nuevo en vez de el viejo porque pensábamos que el plugin cogía el que recibía después del install pero parece que no, que está definido en el propio plugin.

**Comment by sofia-doofinder** [comment]
@eduardogomez97 creo que para esta issue sólo hay que modificar el script (como lo que ha hecho David para pasarle a soporte) pero que no hay que hacer ningún endpoint. Habría que dejar este PR preparado para desplegarlo cuando nos digan que se pone en producción el script único.
