### ISSUE TITLE
[Prestashop] Cambiar la URL del producto padre para que coincida con la variante de menor precio

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#218]
Actualmente para os productos configurables estamos utilizando para el producto padre el sales price & price de la menor de sus variantes. Pero el link que estamos utilizando para este producto padre es el de "por defecto" de la plataforma, que no tiene por qué coincidir con la de menor precio, por lo que es un poco raro que el usuario vea un precio en la capa y al hacer click le lleve a otra de las variantes. Vamos a modificarlo para que el link del producto padre sea el mismo de la variante de menor precio.

**Comment by ogomezba** [comment]
@CristobalDolz @alexsomet Muy buenas! Trabajando en la implementación de este cambio me he topado con el dilema de qué hacer con la indexación, no ya de la url del producto padre, sino de la imagen. Deberíamos asociar al producto padre también la imagen de la variante que seleccionamos para la indexación de los precios? En el caso de la imagen no lo veo tan claro porque, tanto prestashop como woocommerce tienen opción para seleccionar una imagen de "portada" y, opcionalmente, seleccionar imágenes para las variantes (o no, porque por ejemplo para la talla no tiene mucho sentido). No sé si, quizá los clientes que ven el precio del padre más como un "desde XXEUR" prefieren que se muestre al buscar la imagen que tengan seleccionada como portada y no la de la variante concreta descontada.

Cómo lo veis vosotros? Deberíamos indexar también el padre con la imagen de la variante más barata que estamos seleccionando para los precios? En mi opinión, quizá no deberíamos tocar la parte de la imagen y mantener el funcionamiento que tenemos ahora.

Gracias!

**Comment by alexsomet** [comment]
Hola @ogomezba El producto padre, debería seguir indexando la imagen del producto padre, creemos.

**Comment by ogomezba** [comment]
@alexsomet Buenas Alex! Ya está disponible la nueva versión para el plugin de prestashop que indexa el producto padre con la URL de la variante con el mínimo precio.

Un saludo!
