### ISSUE TITLE
[Prestashop] Analizar si se pueden indexar articles

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#224]
Ticket related: https://github.com/doofinder/support/issues/2401

Notion: https://witty-pelican-a6c.notion.site/Analizar-si-en-prestashop-ya-se-pueden-indexar-los-posts-d698dc6d1ced40238a5d96ca1569e441?pvs=4

Parece que los posts de los blogs (articles) no se podían indexar directamente, si no que era necesario hacerlo a través de plugins de terceros. Habría que ver si esto ha cambiado y prestashop ya permite el uso de blogs & posts sin necesidad de plugins de terceros.

**Comment by davidmolinacano** [comment]
Currently, the blog posts are not a Prestashop native type, the only way to have them available is by installing a third-party module (The aforementioned customer seems to be using a module known as "ybc_blog", but I could not finf it on the Marketplace, probably because it has critical vulnerabilities and it might be removed from there).

**Comment by davidmolinacano** [comment]
I've installed Prestashop 8 in my local environment to check this and it still doesn't include native posts, so a third-party module is required to have them.



![Image](https://github.com/doofinder/doofinder-prestashop/assets/128705267/1b0d055d-4071-4847-898a-9be545edd95f)

And according to the future Prestashop 9 roadmap, it is not expected to have native blog posts yet

**Comment by davidmolinacano** [comment]
At this point there is no plugin which has the monopoly in the Prestashop blog. There are some of them like Prestablog, WordPress blog posts (https://addons.prestashop.com/en/blog-forum-new/18964-wordpress-blog-posts.html), Simple blog (https://prestahero.com/186-free-prestashop-blog-module.html), Smartblog (https://github.com/smartdatasoft/smartblog)...

**Comment by davidmolinacano** [comment]
Since there is no future plans to implement it natively I'm closing it for now. @IgnacioPursalsZ
