### ISSUE TITLE
How to handle big catalog with lots of languages?

### ISSUE THREAD

**Issue by davidcylke** [doofinder/doofinder-prestashop#239]
I have around 70k active products and 15 languages in my store. Dedicated server with 64GB of ram and Ryzen 5 CPU. When I first installed Doofinder module it was indexing (I think) the products to the feeds but most of the feeds now have just like 3785 products, one language has 55000 of them. How can I recreate them?

Does anyone of you have such big product catalog and was able to implement Doofinder?

**Comment by alexsomet** [comment]
Hi David, this shouldn't be a problem, but we might need to configure a pagination setting, in order to improve the indexing process on your feeds. Could you please contact support@doofinder.com, so we can help you with this matter? 

Thank you.
