### ISSUE TITLE
[Prestashop] Ocultar página de configuraciones avanzadas

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-prestashop#251]
Enlace a notion: https://witty-pelican-a6c.notion.site/Prestashop-Ocultar-p-gina-de-configuraciones-avanzadas-1230bdae8dfb80b7a66cf52649fa96ff?pvs=4

**Comment by yuloma** [comment]
Haciendo la demo con @IgnacioPursalsZ, vimos algunas mejoras que interesa adicionar.

1. scroll de feed de urls a partir de 3
2. campos store id, region y api key, read only por defecto
3. habilitar escritura de store id, region y api key cuando adv=1
