### ISSUE TITLE
Hello, you have a error dfTools::json_encode not exists!

### ISSUE THREAD

**Issue by slimco** [doofinder/doofinder-prestashop#40]
https://github.com/doofinder/doofinder-prestashop/blob/c75c9a8297181fcb34637b9f6043aeea5b2501a0/config.php#L84

Doofinder will not install properly because doofinder.com will not recognize data from prestashop.

Please, rewrite dfTools::json_encode to dfTools::jsonEncode

And add on the top load class dfTools
```
if (!class_exists('dfTools')) {
	require_once(dirname(__FILE__) . '/lib/dfTools.class.php');
}
```

**Comment by ivan-doofinder** [comment]
Thanks for the suggestion.
We have already modified it in the new release.

We have not added the load of the dfTools class, because that class loads in the module instance:
https://github.com/doofinder/doofinder-prestashop/blob/c75c9a8297181fcb34637b9f6043aeea5b2501a0/config.php#L23

Regards!
