### ISSUE TITLE
Bug on available_for_order attribute when Multishop

### ISSUE THREAD

**Issue by LittleSnake42** [doofinder/doofinder-prestashop#5]
Hello, 

In **dfTools.class.php** , on line 372 & 421, you get the value of *'available_for_order'* from DB table **product** . Prestashop core does it from table **product_shop**. So if a product is not available before you become multishop, the value in **product** will be 0. Then you add shops, and Prestashop always get / update the value from table **product_shop**.

Your product is available on your shop, but Doofinder thinks it's not. 

Prestashop 1.6.1.17 /  Doofinder 3.0.9 (was also present on 2.3.4)

**Comment by LittleSnake42** [comment]
Up please ! :)

**Comment by danidomen** [comment]
Hi @LittleSnake42 ,

You must write to PrestaShop, because is clear a bug of PrestaShop. Is not normal that for one shop the table product is not updated, and yes on product_shop (when this table is clearly used when your store is multishop). And when you are multishop, both tables are modified. It doesnt make sense. But up to you make the PR :)

**Comment by LittleSnake42** [comment]
Hi @danidomen ! 

First of all thank you for your answer. 

Regarding my problem, I do not think there is any bug in here, this is just 'normal' Prestashop behavior (even if it's true that this make no sens having this value in 2 differents tables and only one is being updated). 

Has an exemple, if you look at the core, in **Cart.php** class, line 510 in the SQL query, Prestashop is getting the value from table _product_shop_.
They never check if you are in a multishop context or not.
I have not found any exemple of Prestashop code that gets the value from _product_ table for the moment.

If you look in **Product::$definition**, the field is defined as follow : 

`'available_for_order' =>        array('type' => self::TYPE_BOOL, 'shop' => true, 'validate' => 'isBool'),`

**'shop' => true** 

Doesn't that meen that the ObjectModel when it instanciate a Product (using Adapter_EntityMapper->load()), set the attribute from the $this->def['table'] . '_shop' ? 

Even in other modules, (as far as i can see now on the project) developers get this value form product_shop. 

I don't see where that would be a problem to check if we are in a multishop context or not, and get the value from one table or the other (or as Prestashop does, always check in product_shop), but maybe you see some cases where that would not be ok ? 

If you don't see any issue with those changes, that would be super great to make the changes available in next version of the module. 

If you really think this is kind of a bug on Prestashop side, let me know, I'll go further in my investigations and open a pull request on Prestashop.

In advance thank you.

Rémi, from Axome Team

PS : still on Prestashop 1.6.1.17 (to be sure about files and lines number)

**Comment by danidomen** [comment]
Hi @LittleSnake42 ,

Thanks for the info :)

Could you open a PR here with the proposed change?

Thanks!

**Comment by danidomen** [comment]
Hi @LittleSnake42 

Today I make a PR:
https://github.com/doofinder/doofinder-prestashop/pull/10/files#diff-bc15acbfa2574f811f275b4a9b25787eR386

https://github.com/doofinder/doofinder-prestashop/pull/10/files#diff-bc15acbfa2574f811f275b4a9b25787eR442

Could you check that now the field is ok?

**Comment by LittleSnake42** [comment]
Hey @danidomen , i'm sorry I didn't answer you ! Was on vacations, then I just forgot :) Thanks for the PR, everything seems ok now !
