### ISSUE TITLE
Allow extra fields on feed data

### ISSUE THREAD

**Issue by camlafit** [doofinder/doofinder-prestashop#6]
Hello

On your previous repository, we have propose a PR to extend feed data with extras fields data (as df_rating)
Was done on https://github.com/Webelys-PS/doofinder/commit/7ad54d7026927eff5b940365b6f199908eb9da66

Can we propose a new PR about this feature ? Or must be took on our local fork ?

Thanks a lot

**Comment by danidomen** [comment]
Hi @camlafit!

Thanks for the improvement. I added on a PR with your code :)

https://github.com/doofinder/doofinder-prestashop/pull/9

Cheers!

**Comment by danidomen** [comment]
Hi @kataklanka this improvement is already on the module, can be closed this.
