### ISSUE TITLE
Prestashop - Replace return_path callback with postMessage

### ISSUE THREAD

**Issue by alvanieto** [doofinder/doofinder-prestashop#62]
See woocommerce implementation

**Comment by abraham-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-prestashop/62?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @eduardogomez97 @ivan-doofinder @sofia-doofinder

**Comment by ivan-doofinder** [comment]
@pedromcp90 he realizado una prueba y algo no funciona bien. Sale un mensaje de timeout en el popup después de hacer el login. Te dejo un video para que lo veas: https://youtu.be/kkQsDT1W3p8

He tirado atrás el PR que se había mergeado a master para poder crear una release sin esta parte hasta que se compruebe y solucione el posible problema.

**Comment by ivan-doofinder** [comment]
@pedromcp90 nos han entrado varios tickets informando de que tienen problema con el plugin de Prestashop tras sacar estos cambios. La instalación no finaliza.
He probado en Prestashop 1.6 y efectivamente tengo ese problema con el postMessage, saltando el siguiente error:
![imagen.png](https://images.zenhubusercontent.com/62cc11c57da773ca4f6cb99e/9e8d9a21-52e7-48f2-ab0a-2ce3ff3fe63f)

También nos ha llegado el caso de un Prestashop 1.7.

Tickets:
Presta 1.7:
https://doofinder.freshdesk.com/a/tickets/81961

Presta 1.6:
https://doofinder.freshdesk.com/a/tickets/81866
https://doofinder.freshdesk.com/a/tickets/81846

**Comment by pedromcp90** [comment]
He probado con un prestashop 1.6 y efectivamente había una incompatibilidad, ya que la versión 1.6 usa una versión de jQuery muy antigua (1.11) la cual no es compatible con la forma en que se estaba haciendo la petición post del autoinstaller.
He modificado esa petición para que sea compatible con todas la versiones y ya funciona correctmente.

En cuanto a la versión 1.7, he realizado pruebas tanto en una instalación local como en una instalación en clouding y no se ha producido ningún error al crear los search engines.
Procedo a sacar una nueva release.
