### ISSUE TITLE
(Prestashop) - Index leader & variants grouped by leader

### ISSUE THREAD

**Issue by alvanieto** [doofinder/doofinder-prestashop#66]
Cuando indexamos items con variaciones hay dos métodos:

- Indexar solo el producto padre
- Indexar las variaciones del producto

### Definición: FUNCIONA CORRECTAMENTE
- El comportamiento correcto es :

    - a) Indexar solo el producto padre: el producto padre no indexa los atributos de las variaciones del producto. (funcionamiento actual en Prestashop)
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/7747c2a3-9412-489b-b4ab-95fec55d5ccc)
        - El producto no tiene atributos de variantes (color, talla, etc)
        - Princing: coger el precio del producto padre.
        - En la layer sale un producto solo. no hay pro
    
    - b) Indexar las variaciones del producto: 

        - "**sin agrupar productos con variantes**": cada item que se crea por cada variación indexa sus propios atributos. 
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/cfaa454a-ce72-4576-8ce0-7a36b3e86307)
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/f47e81fe-c95f-4a54-a1ce-fe52e1c67b96)
            - En la layer cada variación sale como un producto diferente con sus atributos individuales. tambien para filtrar.

        - "**agrupando productos con variantes**": se crea un item por el group_leader. Indexa todas las variaciones del producto
            - En la layer solo sale un producto pero los filtros si aplica según los atributos
            - en playground solo se ve el group_leader pero internamente estan todos los valores bien recogidos de cada variacion

**Comment by alexsomet** [comment]
Clientes pendientes de este cambio: 
https://doofinder.freshdesk.com/a/tickets/78050
https://doofinder.freshdesk.com/a/tickets/78111
https://doofinder.freshdesk.com/a/tickets/79535

**Comment by CristobalDolz** [comment]
esto aplica solo a Prestashop?

**Comment by alexsomet** [comment]
Creo que hay una confusión aquí, debería ser:

El comportamiento correcto es:
-No exporto las variaciones: el producto padre **NO** indexa todos los valores de los atributos disponibles.

Si no, volvemos a repetir el siguiente problema:
_el padre indexa atributos de las variaciones afecta como explica Alex en el ejemplo:

La variación de la talla 40 está fuera de stock.

El producto padre, que sí está en stock, tiene indexado ese atributo y por tanto la faceta talla mostrará el 40.

Cuando el cliente filtre por esa talla, que corresponde al producto padre, se mostrará un producto que está fuera de stock, cuando no debería, la inforamción está duplicada y es contradictoria._

-Exporto las variaciones: el producto padre no indexa los atributos de las variaciones. ya que cada variación indexa su propio atributo. => **CORRECTO**

@kataklanka

**Comment by CristobalDolz** [comment]
En prestashop no se va a realizar ningún cambio. El funcionamiento actual es el más genérico puesto que en la propia web no existe un producto genérico sin tener seleccionada la variante. 
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/8147da07-215e-4234-b654-9fa491c3c3b6)

Solo afecta a las imágenes, por lo que para lo que el cliente quiere (ver una imagen cover en la layer), se puede gestionar añadiendo la imagen del cover al producto variante por defecto.

El propio cliente lo ha solucionado de esa forma
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/fbbedddf-12af-46a4-9560-bd866bb802c3)
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/151f6e3c-2087-4bb9-9a8f-2fe4fe31e93a)

se revisará que en otras plataformas el comportamiento sea como mínimo el mismo.

**Comment by alexsomet** [comment]
Hola @CristobalDolz tenemos otro caso igual: 
https://doofinder.freshdesk.com/a/tickets/83088

Dónde el cliente se queja de que si exportamos las variaciones, la imagen por defecto no es la del producto padre, ya que la variación por defecto se convierte en group leader. 

Igual nos interesa darle otra vuelta, aunque sea sin exportar el producto padre...
