### ISSUE TITLE
 Collect sector in Prestashop

### ISSUE THREAD

**Issue by pedromcp90** [doofinder/doofinder-prestashop#69]
Keep in mind that it can be multi-store so once you log in and before launching the creation, a pop-up or a window will pop up with an input of each store where you can select the sector. With this we add the sector data to the store and send it through the API.

**Comment by pedromcp90** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-prestashop/69?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder

**Comment by ivan-doofinder** [comment]
@CristobalDolz Pedro creó este video para mostrar como quedaría el selector de sector en el plugin de Prestashop: 
https://user-images.githubusercontent.com/1659534/188640181-9328fb21-a459-4b78-807d-94873bfcd0a3.mp4

cc @alvanieto

**Comment by CristobalDolz** [comment]
En este video se recoge el sector para varias tiendas a la vez, entiendo que es en el caso de que se esté instalando doofinder teniendo ya varias stores en prestashop?

**Comment by ivan-doofinder** [comment]
> En este video se recoge el sector para varias tiendas a la vez, entiendo que es en el caso de que se esté instalando doofinder teniendo ya varias stores en prestashop?

@CristobalDolz  Eso es. Te sale el listado de todas las tiendas cuando Prestashop tiene más de una store (multitienda)

**Comment by pedromcp90** [comment]
https://images.zenhubusercontent.com/154816999/7fdb3025-a037-48f0-83ea-c684414622a1/install_prestashop.mp4

**Comment by pedromcp90** [comment]
I've uploaded a video of the new functionality

**Comment by pedromcp90** [comment]
As this issue has become more complicated than we expected, and also includes the changes requested in the issue #73, we've decided that it's fair to adjust its estimate increasing it in one point

**Comment by pedromcp90** [comment]
Product has requested us to stop this issue until they decide whether if we are going to request the sector in the installation process or in another step

**Comment by CristobalDolz** [comment]
Finally we are not going to ask the sector in the module. We will ask the sector in Doomanager with a flash message. 

I close this issue.

**Comment by CristobalDolz** [comment]
Finally we are not going to ask the sector in the module. We will ask the sector in Doomanager with a flash message. 

I close this issue.
