### ISSUE TITLE
Prestashop - Show installation error

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-prestashop#73]
If the installation fails due to the data sent from the platform, show the user the reason. For example, when an unsupported ISO code is sent in the language.

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-prestashop/73?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder

**Comment by pedromcp90** [comment]
Closed as this is already implemented in the [issue #69](https://app.zenhub.com/workspaces/plugins-stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-prestashop/69)

**Comment by ivan-doofinder** [comment]
Reabro ya que posiblemente la issue #69 no se suba
