### ISSUE TITLE
Bug on facet for internal search

### ISSUE THREAD

**Issue by tfayolle** [doofinder/doofinder-prestashop#8]
Hello, 

When you use the internal search it is impossible to use the facet or other option on prestashop 1.7 the Javascript does't load because we have one condition "prestashop version less than 1.7".
If you try to force the JS, the facet appear on the left column but nothing work when you click on filters.

Prestashop 1.7.5.2 / Doofinder 3.0.9

**Comment by danidomen** [comment]
Hi @tfayolle ,

You are doing wrong. On 1.7 the JS is not loaded anymore, because is not using overrides anymore. On PrestaShop 1.7 you must be sure to have the module hooked on productSearchProvider hook. Also, if you want the filters lists on left/right column, you must be sure to add on your PS Theme config that the "Search" page must have this column enabled (by default, is disabled), also be sure that the module is hooked on displayLeft/RightColumn

Cheers!

**Comment by tfayolle** [comment]
Hi @danidomen 

OK the JS is not loaded, but I verifiy and the module is correctly hooked on "productSearchProvider" and "displayLeftColumn"
![image](https://user-images.githubusercontent.com/41959732/62779506-b7f96d00-bab3-11e9-93da-232682dc8244.png)
![image](https://user-images.githubusercontent.com/41959732/62779546-cc3d6a00-bab3-11e9-9b88-8df180b92b77.png)

And on PS Theme I check if the colum is activate and it's OK
![image](https://user-images.githubusercontent.com/41959732/62779673-276f5c80-bab4-11e9-87b1-c0f0e4c59df5.png)

But the facets still not working :(
I try with two projet one with doofinder in 3.0.9 and one with 3.0.6

**Comment by danidomen** [comment]
Friend! You have Advanced Search also hahaha. These two modules are incompatibles on the same general search result page. Also, to be worst, the Advanced Search is after Doofinder, so the mix of things can be completely a mess.

Try to disable it, or better, on a clean PS installation with only Doofinder, with no any other search module :)

If this works, you make sure to add Advanced Search a "exception" to not load anything on Search Page.

**Comment by danidomen** [comment]
Hi @kataklanka, this issue can be closed because the malfunctioning become to have another module that is knowed be incompatible to stay together with doofinder in the same search result default "override"

**Comment by kataklanka** [comment]
Hi @danidomen. We close this issue. Thanks!
