### ISSUE TITLE
Prestashop - reindex when a setting has changed

### ISSUE THREAD

**Issue by CristobalDolz** [doofinder/doofinder-prestashop#81]
As a shop owner when I do a change of any setting and it requires to index the search engines again I want to be able to process the index from the platform.

Some settings changes require to process again the indice and currently the user has to do it manually from doofinder admin to see the changes effective in the layer.

![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/fe58e503-93f6-400e-a2e9-8eaad776b12b)

![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/652fb50b-b8d6-4be5-906e-18397fb594cb)

### Definition:
- When a setting change requires to index the search engines, then add a button in the message to allow to launch the indexing process and show a message to inform that the indice will be processed again: 
"PARA QUE LOS CAMBIOS TENGAN EFECTO, RECUERDA QUE DEBES REPROCESAR EL INCIDE" [Lanzar indexación]"
- Show section when indice is being processed**
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/785000c1-4b81-4165-8393-b74971037d8f)
- Remove current message:
"SI HAS CAMBIADO ALGO EN LAS OPCIONES DE EXPORTACIÓN DE TU FEED, RECUERDA QUE DEBES REPROCESARLO"

**Comment by davidmolinacano** [comment]
Tech validation conclusion: it has to be done by using GraphQL

**Comment by davidmolinacano** [comment]
As I promised, I'm attaching the module as a ZIP file.

~~[doofinder-prestashop.zip](https://github.com/doofinder/doofinder-prestashop/files/12078424/doofinder-prestashop.zip)~~ --> Not working, wrong file structure

**Comment by davidmolinacano** [comment]
@CristobalDolz I'm moving it to Product Testing if you don't mind

**Comment by CristobalDolz** [comment]
@davidmolinacano i am having troubles to update the module version 


![Image](https://github.com/doofinder/doofinder-prestashop/assets/106097983/f7d7996f-6ab9-4f4f-b95a-7f8485b83385)

**Comment by davidmolinacano** [comment]
@CristobalDolz I'm very sorry, I uploaded the ZIP with a wrong structure. This one should work flawlessly (I've tested it also on my local Prestashop store): 
[doofinder-prestashop.zip](https://github.com/doofinder/doofinder-prestashop/files/12093196/doofinder-prestashop.zip)

**Comment by CristobalDolz** [comment]
tested OK. @davidmolinacano you can merge the version

**Comment by davidmolinacano** [comment]
I'm on it 💪 , thank you for your patience 🙏

**Comment by davidmolinacano** [comment]
Uploaded to Prestashop marketplace. Waiting for validation from their side.

**Comment by davidmolinacano** [comment]
Validated 😄
