### ISSUE TITLE
Prestashop - Not show prices in layer

### ISSUE THREAD

**Issue by CristobalDolz** [doofinder/doofinder-prestashop#82]
Setting in Prestashop about show or hide prices in product results is not working well.

Show product prices = ENABLED:
INITIAL: prices are shown
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/3890264f-1ee1-4502-bfe7-b3c1e3317bfe)
RESULTS: prices are shown
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/f1e77989-1222-4c45-9891-ac206864b27c)

Show product prices = DISABLED
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/7b3835ce-624d-4eba-93f3-b81004dea19f)
INITIAL: prices are shown (X)
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/3890264f-1ee1-4502-bfe7-b3c1e3317bfe)
RESULTS: prices are not shown
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/25bb659c-a7f7-497e-8c94-5755516ce428)

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Unplugged-62c7342b32b594001e03d82a/issues/doofinder/doofinder-prestashop/82?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @eduardogomez97 @ivan-doofinder @sofia-doofinder

**Comment by ivan-doofinder** [comment]
@CristobalDolz I've been testing and I don't see any problem.
At the moment that the "show prices" option is deactivated in Prestashop and you reindex, the prices will no longer be indexed so they cannot be displayed.
It may be the case that the recommended products have been cached in the layer and show them with "old" data, but it should be for a short time. I think this is what happened to you, but it is not a problem with the Prestashop module.

**Comment by CristobalDolz** [comment]
please, can you add a video with the test you have done in order to keep register that is working well? and after that we can close the issue

**Comment by ivan-doofinder** [comment]
@CristobalDolz  There is a 30-minute cache on recommended products, that's why the price is shown only on recommended products. This will happen on any platform.
I show you a video where the recommended ones appear without price in Prestashop: https://youtu.be/CE1Kyu_K2H0
