### ISSUE TITLE
Compatibility with Prestashop 8.0

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-prestashop#95]
Check if the plugin is compatible with version 8.0 of Prestashop and analyze possible changes to make to adapt it.

**Comment by albertodoofinder** [comment]
After talking with @kataklanka a customer has reported that our plugin currently is not compatible with version 8. No further information has been provided.

**Comment by ivan-doofinder** [comment]
An adjustment has been made and it is now compatible with version 8 of Prestashop
