### ISSUE TITLE
Use of GitHub Actions to create new Prestashop module versions

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-prestashop#96]
Create workflows with GitHub Actions to generate Prestashop module versions

**Comment by ivan-doofinder** [comment]
@pedromcp90 I have been researching this point.

I have found documentation about the Prestashop addons API: https://addons.prestashop.com/es/content/34-sellers-api

I have also seen here some examples of workflows showing how to create a release and how to publish it in the marketplace: https://github.com/PrestaShopCorp/ps_checkout/tree/master/.github/workflows

In the Prestashop addons you can get the API KEY (https://addons.prestashop.com/es/seller-account?step=4)

**Comment by pedromcp90** [comment]
I've created a release workflow that generates a zip file and creates a new release, also, I've created another workflow to upload the extension to the marketplace, but at the moment of uploading the generated zip to the marketplace API I've found that the needed endpoint is not open to the public by the moment.

See the discussion [here](https://github.com/PrestaShopCorp/publish-on-marketplace/issues/3)

So currently we have to keep uploading the zip file manually until they release this endpoint to the public.

**Comment by pedromcp90** [comment]
I've updated the Release documentation, you can check it [here](https://github.com/doofinder/issues/wiki/Prestashop#publishing-the-release-in-github).
